"use client";

import { Pipeline } from "@/data/pipelines";
import { AI_TOOLS } from "@/data/ai-tools";
import ToolLogo from "./ToolLogo";
import Button from "./Button";
import { Download, ArrowRight, Lightbulb, Check, Sparkles } from "lucide-react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import jsPDF from "jspdf";

interface PipelineCardProps {
  pipeline: Pipeline;
  onHelpBuild?: () => void;
}

export default function PipelineCard({ pipeline, onHelpBuild }: PipelineCardProps) {
  const { data: session } = useSession();
  const router = useRouter();
  const [expandedStep, setExpandedStep] = useState<number | null>(null);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);

  function handleExportPDF() {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 48;
    const contentW = pageW - margin * 2;
    let y = 56;

    // ── Header ──
    doc.setFillColor(108, 60, 239);
    doc.roundedRect(margin, y - 20, contentW, 56, 6, 6, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("YOUR AI BLUEPRINT", margin + 16, y - 2);
    doc.setFontSize(15);
    const titleLines = doc.splitTextToSize(pipeline.title, contentW - 32);
    doc.text(titleLines, margin + 16, y + 16);
    y += 56;

    // ── Summary ──
    doc.setTextColor(80, 80, 80);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    const summaryLines = doc.splitTextToSize(pipeline.summary, contentW);
    doc.text(summaryLines, margin, y + 14);
    y += summaryLines.length * 13 + 20;

    // ── Steps ──
    pipeline.steps.forEach((step, i) => {
      const tool = AI_TOOLS[step.tool];
      const stepLines = doc.splitTextToSize(step.detail, contentW - 20);
      const reasonLines = doc.splitTextToSize(`Why: ${step.reason}`, contentW - 20);
      const blockH = 14 + 14 + stepLines.length * 12 + reasonLines.length * 11 + 20;

      if (y + blockH > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }

      doc.setFillColor(249, 249, 252);
      doc.roundedRect(margin, y, contentW, blockH, 5, 5, "F");
      doc.setDrawColor(220, 220, 235);
      doc.roundedRect(margin, y, contentW, blockH, 5, 5, "S");

      doc.setFillColor(108, 60, 239);
      doc.circle(margin + 14, y + 14, 8, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.text(String(i + 1), margin + 14, y + 17, { align: "center" });

      doc.setTextColor(20, 20, 20);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.text(step.tool, margin + 28, y + 16);

      if (tool?.category) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(108, 60, 239);
        doc.text(`  ·  ${tool.category.toUpperCase()}`, margin + 28 + doc.getTextWidth(step.tool), y + 16);
      }

      doc.setTextColor(108, 60, 239);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.text(step.role, margin + 14, y + 30);

      doc.setTextColor(80, 80, 80);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(stepLines, margin + 14, y + 43);

      const reasonY = y + 43 + stepLines.length * 12 + 4;
      doc.setTextColor(130, 100, 200);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.text(reasonLines, margin + 14, reasonY);

      y += blockH + 8;
    });

    doc.setTextColor(180, 180, 180);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text("Generated by AI Blueprint · aiblueprint.app", pageW / 2, doc.internal.pageSize.getHeight() - 24, { align: "center" });

    const filename = `${pipeline.title.toLowerCase().replace(/\s+/g, "-")}-blueprint.pdf`;
    doc.save(filename);
  }

  async function handleSave() {
    if (!session) {
      router.push("/signup");
      return;
    }
    setSaving(true);
    try {
      const res = await fetch("/api/blueprints", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: pipeline.title,
          prompt: pipeline.summary,
          scenario: "saved",
          pipeline: pipeline,
          status: "completed",
        }),
      });
      if (res.ok) setSaved(true);
    } catch {
      setSaved(true);
    }
    setSaving(false);
  }

  return (
    <div className="w-full max-w-[680px] bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-md">
      {/* Header */}
      <div className="px-4 sm:px-6 pt-5 pb-4 bg-gray-50 border-b border-gray-100">
        <p className="text-[11px] font-bold text-brand-500 uppercase tracking-[0.08em] mb-1.5">
          Your AI Blueprint
        </p>
        <h3 className="text-lg font-bold text-gray-900">{pipeline.title}</h3>
        <p className="text-[12px] text-gray-400 mt-1">
          {pipeline.steps.length} tools · tailored to your use case
        </p>
      </div>

      {/* Steps */}
      <div className="px-4 sm:px-6 py-5">
        {pipeline.steps.map((step, i) => {
          const tool = AI_TOOLS[step.tool];
          const isExpanded = expandedStep === i;

          return (
            <div key={i}>
              <div className="flex gap-3.5">
                {/* Left: logo + connector line */}
                <div className="flex flex-col items-center">
                  <ToolLogo name={step.tool} size={42} />
                  {i < pipeline.steps.length - 1 && (
                    <div
                      className="w-0.5 my-1.5 bg-gradient-to-b from-gray-200 to-transparent transition-all duration-200"
                      style={{ height: isExpanded ? 72 : 36 }}
                    />
                  )}
                </div>

                {/* Right: tool info */}
                <div className="flex-1 pt-0.5 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5 flex-wrap">
                    <span className="font-bold text-gray-900 text-sm">
                      {step.tool}
                    </span>
                    <span
                      className="px-1.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wide whitespace-nowrap"
                      style={{
                        backgroundColor: `${tool?.color}14`,
                        color: tool?.color,
                        border: `1px solid ${tool?.color}25`,
                      }}
                    >
                      {tool?.category}
                    </span>
                  </div>

                  <p className="text-xs font-semibold text-brand-500 mb-0.5">
                    {step.role}
                  </p>

                  <p className="text-[13px] text-gray-500 leading-relaxed">
                    {step.detail}
                  </p>

                  <button
                    onClick={() => setExpandedStep(isExpanded ? null : i)}
                    className="mt-1.5 flex items-center gap-1 text-[11px] font-semibold text-brand-400 hover:text-brand-600 transition-colors"
                  >
                    <Lightbulb size={12} />
                    {isExpanded ? "Hide reasoning" : "Why this tool?"}
                  </button>
                  {isExpanded && (
                    <div className="mt-1.5 px-3 py-2 rounded-lg bg-brand-50 border border-brand-100 text-[12px] text-brand-700 leading-relaxed">
                      {step.reason}
                    </div>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Summary */}
      <div className="px-4 sm:px-6 py-4 bg-gray-50 border-t border-gray-100">
        <p className="text-[13px] text-gray-500 leading-relaxed">
          {pipeline.summary}
        </p>
      </div>

      {/* Actions */}
      <div className="px-4 sm:px-6 py-3.5 flex gap-2.5 justify-end border-t border-gray-100 flex-wrap">
        <Button variant="secondary" size="sm" onClick={handleExportPDF}>
          <Download size={14} /> Export PDF
        </Button>
        {saved ? (
          <Button size="sm" variant="secondary" disabled>
            <Check size={14} className="text-green-500" /> Saved
          </Button>
        ) : (
          <Button size="sm" onClick={handleSave} disabled={saving}>
            {saving ? "Saving..." : "Save Blueprint"}{" "}
            <ArrowRight size={14} />
          </Button>
        )}
        {onHelpBuild && (
          <Button size="sm" onClick={onHelpBuild}>
            <Sparkles size={14} /> Help Me Build This
          </Button>
        )}
      </div>
    </div>
  );
}
